### ISSUE TITLE
Long term cluster management

### ISSUE THREAD

**Issue by derekperkins** [couchbase/kubernetes#19]
As I'm trying to get things running, I'm also trying to think about my maintenance on GKE. Obviously this is still a beta repo on a beta service using a beta db server, so it's been tough to get something working. I have no doubts that will get ironed out quickly. What is your vision in regards to scaling and upgrading?

1. Horizontal scaling
 1. Edit `couchbase-server.yaml` `spec: replicas: n`
 1. Running `kubectl update`

1. Vertical scaling (increasing machine type and/or changing attached disk size)
 1. Bring down 1 VM at a time?

1. Automatic scaling
 1. Will the cluster be able to scale horizontally based on demand?

1. Upgrading (the server, sidekick or any other services)
 1. Do I have to take down the whole server to apply container updates?

Thanks,
Derek

**Comment by tleyden** [comment]
> Vertical scaling Bring down 1 VM at a time?

Until we have a better story with persistent volumes, the recommended approach is:

1. Bring up a new (bigger node), add to Kubernetes cluster 
1. Remove couchbase node from cluster using Couchbase Admin UI
1. Bring down the decommissioned node
1. The Kubernetes Replication Controller should create a new couchbase server instance and put it on the new node created in Step 1.

**Comment by tleyden** [comment]
> Will the cluster be able to scale horizontally based on demand?

Once the **1. Horizontal scaling** is working reliably, it would be possible to create something that monitored the load and scaled things horizontally.

> Upgrading (the server, sidekick or any other services).  Do I have to take down the whole server to apply container updates?

I would suggest the "rolling upgrade" approach mentioned in "Vertical scaling Bring down 1 VM at a time"

Gonna close this ticket since there's no immediate action items.  (feel free to file more tickets for any questions or whatever, this is currently the best place for that)

**Comment by derekperkins** [comment]
How would the rolling upgrade function on a upgrade, where different nodes are running different versions of CB?

**Comment by tleyden** [comment]
Different versions of CB isn't a problem for a rolling upgrade.

**Comment by derekperkins** [comment]
That's pretty cool.
