### ISSUE TITLE
Figure out which scripts are useful

### ISSUE THREAD

**Issue by tleyden** [couchbase/kubernetes#24]
@bcbroussard / @PatrickHeneise on GCE, which scripts would I want to run that correspond to the README?

Also, which scripts would I run on AWS?

**Comment by PatrickHeneise** [comment]
The AWS CloudFormation worked fine for me, I'm working on the GCE architecture at the moment, can give you more details probably next week.

**Comment by tleyden** [comment]
@PatrickHeneise can you add details on the steps you did to make it work?

- How did you spinup the AWS?
- Which scripts / steps from this repo did you run?

**Comment by bcbroussard** [comment]
@tleyden I think the easiest thing to do would be to use the quick start scripts.

```
export KUBERNETES_PROVIDER=aws; curl -sS https://get.k8s.io | bash
```

It should be largely the same as the gce scripts I initially wrote. I'll run through both of these today and get back to you tomorrow.

**Comment by bcbroussard** [comment]
For clarification: the gce scripts here should still work for launching. I haven't tested with v1 yet though.

https://github.com/couchbase/kubernetes/blob/master/scripts/k8s-gce-register.sh

**Comment by bcbroussard** [comment]
@tleyden GCE setup is similar, the comments at the top of `k8s-gce-register.sh` explain:
```
# Assumes you have a running kubernetes cluster
# created with `echo curl -sS https://get.k8s.io | bash`
# or a local Kubernetes source folder where
# kubernetes/cluster/kube-up.sh was run
```
The get.k8s.io script has `KUBERNETES_PROVIDER` set to gce by default.

**Comment by bcbroussard** [comment]
@tleyden the `k8s-gce-register` script is for GCE, where the `register` script is for GKE. `k8s-gce-register` assumes you have a running GCE cluster started with `echo curl -sS https://get.k8s.io | bash` as per the source's comments. Cluster configuration is possible just like the AWS script too.

**Comment by tleyden** [comment]
That helps!  Can you take a look at https://github.com/couchbase/kubernetes/blob/master/scripts/README.md and let me know if that looks right?

**Comment by bcbroussard** [comment]
The register.sh script creates a k8s cluster on gke. So either update the readme to reflect that or edit the script to remove

**Comment by tleyden** [comment]
When you say "creates a k8s cluster", do you mean adds the couchbase stuff?  I thought GKE already had the k8s cluster built-in?

**Comment by bcbroussard** [comment]
The gke register script had a "gcloud create gke instances" command at the beginning. That creates your gke instances to run your pods. 

The gce one I wrote does not start any instances, it expects a full k8s cluster to be running with a few node servers (formerly called minions).

GKE is basically the same as GCE's kubernetes full cluster, but without a master. You just run the nodes. Does that help?
