### ISSUE TITLE
API Port?

### ISSUE THREAD

**Issue by dovy** [couchbase/kubernetes#26]
I can use the Sync port/ip to access that, but if I want to read/write directly the the server there is no method, correct? Trying to do a mass import.  ;)

Any direction would be appreciated.

**Comment by tleyden** [comment]
That will only work if you are using bucket shadowing, which I wouldn't actually recommend using since it has a long term deprecation plan.

Can you do your mass import via Sync Gateway's REST api?

**Comment by tleyden** [comment]
Closing as there are no action items, but feel free to ask more questions or post more tickets.

**Comment by dovy** [comment]
Is there a library that allows that? Currently using PHP. Are you suggesting that I instead link to replicate over the sync gateway and import locally?

**Comment by tleyden** [comment]
There are CouchDB specific libraries that should be compatible with the Sync Gateway REST API, which is based on the CouchDB API.

https://wiki.apache.org/couchdb/Getting_started_with_PHP

Having said that, the REST API is simple enough you can get by pretty easily without a library.

I wasn't suggesting to replicate per se, just call the `bulk_docs` endpoint on Sync Gateway to add the docs.  The Sync Gateway REST API is documented here: http://developer.couchbase.com/mobile/develop/references/sync-gateway/rest-api/index.html
