### ISSUE TITLE
Advice on persistent volumes and hostnames

### ISSUE THREAD

**Issue by afterthought** [couchbase/kubernetes#27]
Hi... I have host volumes attached to the couchbase container. If I remove my pods and recreate them the data volume stores the couchbase data/logs/configs. However, when the containers start back up I get errors like this:

    Configured address `10.244.30.7` seems to be invalid. Will refuse to start for safety reasons.

Obviously, after removing the pod and recreating I now have new IP addresses with flannel. However, an old IP address is stored in my data volume which prevents couchbase from starting. How should I tackle this? I see older couchbase documentation that discusses setting hostnames after a server is setup. I'm on AWS/CoreOS. Should I be looking at a kubernetes-flavored solution? Or do I need to be doing something differently when running the couchbase container?

Thanks...

**Comment by tleyden** [comment]
@afterthought you are hitting known limits with using persistent volumes with couchbase containers.  The solution I know of that should work is to depend on hostnames rather than ip addresses, which I've recommended to me by the Couchbase Server support team, but I have not tested in the context of Kubernetes or CoreOS.  It would be great if you could try this and report back.

A Kubernetes flavored solution would be ideal.

Going to close this ticket until we have a concrete action item, but feel free to continue the discussion here.  Thanks for posting this!

**Comment by afterthought** [comment]
Thanks! I just did an experiment where I hard coded the clusterIP for each Service and tried using these IP's with the --local-ip flag on the sidekick. I can see in the sidekick logs that this almost works. I think it's failing because not all of the needed ports are exposed on the services. This wouldn't be a viable solution though since the docs say that node-to-node requires 21100 to 21299 inclusive.

I experimented last night with AWS private DNS and pointing A records to the flannel generated IP addresses. The downside of this is that I'd need to manually maintain the DNS records whenever the couchbase container restarted. That might be OK (for now), however I don't know exactly how to tell the couchbase server container to use a hostname when starting up the container. I was looking at the readme's for the couchbase docker project, but didn't find it yet.

**Comment by tleyden** [comment]
> That might be OK (for now), however I don't know exactly how to tell the couchbase server container to use a hostname when starting up the container. 

Can you post this question on https://forums.couchbase.com/?  The Couchbase Server support engineers monitor this closely.

If you don't get a response within a few days, post an update on this ticket and I'll reach out to them directly.

**Comment by afterthought** [comment]
I registered with the forum, but ended up trying a few more experiments before I posted. I realized it would be easier to test out the "service" solution first so I generated a service with all couple hundred ports exposed. I used the clusterIP again and passed this as the --local-ip flag. This almost works. I get this error:

    2015/08/27 21:34:55 AddNode failed with err: Failed to POST to http://10.100.0.101:8091/controller/addNode.  Status code: 400.  Body: ["Prepare join failed. Could not listen on address \"10.100.0.100\": eaddrnotavail"].  Will retry in 60 secs

Which is [documented](https://issues.couchbase.com/browse/MB-8981?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel) as expected behavior I think.

I think I'll post to the forum later with that error to see if anyone knows the root cause. I confirmed that I can access that service's virtual IP address from the couchbase server container. If this goes no where, I think I'll be stuck with using DNS. From what I've seen I think couchbase is smart enough to just work if you pass in a hostname using your --for-ip flag.

**Comment by afterthought** [comment]
I'm thinking of just going back to fleet/coreos.

**Comment by afterthought** [comment]
@tleyden I setup a 2 node cluster using fleet with host networking. This works well. I can reboot nodes and they restart and rejoin the cluster no problem. My plan is to also create a kubernetes replication group that can create ephemeral pods that join the cluster if need be.

I am stuck on something though which I think is rooted in the couchbase-cluster-go library. If I reboot all nodes in the cluster at the same time the etcd keys expire and the machines cannot bring back the cluster. I tried manually creating the missing etcd keys, but this didn't work. I think they ended up "split" somehow. I was looking at this [issue](https://github.com/couchbaselabs/couchbase-server-coreos/issues/2) which I think identifies my problem and is also the original thinking on the current design for couchbase-cluster-go. If I knew I needed to reboot all machines in the cluster my guess is that I could manually create the etcd keys and they would come backup fine. My concern though is the once-every-two-years major AWS outage. If everything were to crash unexpectedly I'd be dead in the water. I'd like to know if this scenario is in scope for couchbase-cluster-go. If so, maybe I've missed the correct procedure and I'd be happy to help figure out the procedure too. If it's out of scope, that's probably OK if I knew enough to know that I could manually recover with the right ad-hoc API calls, etc. 

Any ideas? Thanks!!!

**Comment by afterthought** [comment]
Btw. This is what I see in the logs:

    2015/08/29 00:03:49 AddNode()
    2015/08/29 00:03:49 AddNode posting to http://10.21.101.100:8091/controller/addNode with data: hostname=10.21.101.100&password=telegent01&user=admin
    2015/08/29 00:03:49 Using username/password pulled from etcd
    2015/08/29 00:03:49 POST to http://10.21.101.100:8091/controller/addNode
    2015/08/29 00:03:49 AddNode failed with err: Failed to POST to http://10.21.101.100:8091/controller/addNode.  Status code: 400.  Body: ["Adding nodes to not provisioned nodes is not allowed."].  Will retry in 10 secs


I wonder if the issue is because I create both keys in etcd (instead of just one). I have a 2 node cluster and I created a node-state key for both. The error above is a node trying to join itself. I'll retest with just picking one node for etcd.

**Comment by afterthought** [comment]
Yay! That was it. I just tested it twice. Once I rebooted each node and while they rebooted created a single node-state key. The cluster came back. The second test I used reboot -f and waited to create my etcd key in order to simulate an unexpected outage. One of the sidekick units fails like expected, but then I can create a node-state key and everything starts working. The sidekick failure seems to be a 400 error trying to create the default bucket. It seems like this error is desired perhaps since the cluster is already configured.

**Comment by tleyden** [comment]
>  I setup a 2 node cluster using fleet with host networking.

So at this point, are you using Kubernetes at all or is this a pure CoreOS + Fleet setup?

> If I reboot all nodes in the cluster at the same time the etcd keys expire and the machines cannot bring back the cluster.

I don't think I've actually tested that scenario, or even planned for it.  Thanks for raising this issue though.  

> I wonder if the issue is because I create both keys in etcd (instead of just one). 

Which keys did you create exactly?

> I can create a node-state key and everything starts working

You shouldn't need to create a node-state key .. if you did then that's a bug. 

Thanks again for reporting your findings!  Keep them coming.

**Comment by afterthought** [comment]
> So at this point, are you using Kubernetes at all or is this a pure CoreOS + Fleet setup?

AWS/CoreOS/Fleet. Two ec2 instances deployed with well known private IP addresses (so they won't change). These instances run kube-proxy and kube-kubelet still as well as the other CoreOS setup needed to enable Kubernetes, flannel, etc. My approach is going to be these 2 "well known" members of the cluster setup in fleet with well known IP addresses and persistent volumes. My thinking is to then use a Kubernetes replication controller as a way to extend the cluster on demand easily with "ephemeral" nodes. I haven't tested this part yet.

> Which keys did you create exactly?

My script is below. Basically /couchbase.com/couchbase-node-state/<my-first-node>.

    ssh core@$(terraform output -module=platform bastion_private_ip) "curl -L http://127.0.0.1:2379/v2/keys/couchbase.com/couchbase-node-state/$(terraform output -module=platform couchbase_prod_0_private_ip) -X PUT -d value=\"$(terraform output -module=platform couchbase_prod_0_private_ip):8091\""

> You shouldn't need to create a node-state key .. if you did then that's a bug.

Hmm. I don't have the logs handy at this point. If I recall what you see when you try to access the GUI is the setup screen instead of the login screen. I might be able to run the scenario again in the next couple of days and will post more details. Maybe the behavior will vary between a graceful and non-graceful shutdown?

**Comment by afterthought** [comment]
Ok. Here is a gist with the sidekick logs from both hosts after the reboot. 

https://gist.github.com/afterthought/a40e51a30483376b9c11

**Comment by afterthought** [comment]
@tleyden  Correct me if I'm wrong, but I think my plan might be flawed (still new to couchbase). I'm OK as long as my static cluster stays the same, but if I add ephemeral nodes to my cluster with Kubernetes I might get in trouble. If the replica count is 1 and a document (and it's replica) only get saved to disk on an ephemeral kubernetes node then I'd lose those documents if those nodes were to go down without rebalancing. So to truly embrace horizontal scaling with kubernetes (which for now requires ephemeral storage) then you'd have to have a disaster recovery plan in place if your ephemeral cluster had the plug pulled. Does that sound right? These sidekick tools you've built are great, but it's easy to lose sight of the forest for the trees.

**Comment by tleyden** [comment]
> but if I add ephemeral nodes to my cluster with Kubernetes I might get in trouble.

I'm not totally clear on your architecture.  Can you spell this out a little more?  Are you saying you have 3 "master kubernetes" nodes and N "kubernetes emphemeral nodes"?

>  If the replica count is 1 and a document (and it's replica) only get saved to disk on an ephemeral kubernetes node then I'd lose those documents if those nodes were to go down without rebalancing.

If your replica count is 1, then you will have *two* copies of each vbucket spread across the cluster at any given time.  (what is a vbucket?  the data is sharded into 1024 shards and spread across the cluster, and each shard is called a vbucket).  

For example, lets say you have

* NodeA
* NodeB
* NodeC

and NodeA was assigned vbucket1, and NodeB was assigned the *replica* of vbucket1.  Then lets say you simultaneously unplugged NodeA and NodeB, followed by formatting the hard drives of both NodeA and NodeB.  All the data in vbucket1 (and other vbuckets) is permanently lost.

OTOH if:

* There was time in between NodeA and NodeB being unplugged/wiped
* Auto-failover was enabled (or there was a mechanism to manually trigger failover) and it happened *before* NodeB was unplugged/wiped

Then the cluster would make sure that NodeC was assigned vbucket1 and there would be no data loss.  (eg, after NodeA went down and auto-failover triggered, NodeB would be promoted from replica copy to master for vbucket1, and NodeC would become the new replica copy for vbucket1)

**Comment by afterthought** [comment]
> Can you spell this out a little more?

I have a CoreOS cluster made up of a mix of regular ec2 instances and also ASG launched instances. I have 3 static nodes that run the etcd cluster and a few other services. I have a dedicated single kubernetes master node. I have two dedicated couchbase nodes (at first I was scheduling couchbase to these with kubernetes, now I use fleet). Then I have an ASG that creates additional "dynamic nodes" that run various services is kubernetes. These all have kubelet and kube-proxy. When I referred to "ephemeral" nodes above I was talking about using kubernetes to expand my couchbase cluster from 2 to N by scheduling couchbase to run on one of the dynamic ASG instances and letting the couchbase-sidekick join it to dedicated 2 node cluster.

Your explanation makes perfect sense. I recognize that with failover, etc. the cluster is still pretty resilient. I'm just making sure that I'm at least covering the worst case scenario. I have my 2 dedicated couchbase nodes now setup with persistent volumes. What I realized was that by adding a 3rd node without a persistent volume I could potentially lose data just like in the scenario you described.

**Comment by tleyden** [comment]
OK thanks for sharing that!  Just curious, can you post any of your ASG config or describe how you have it setup to trigger new instances to be kicked off?

**Comment by afterthought** [comment]
I'm using terraform so I'd have to pull in a bunch of different files to be complete. But here's the main file I use that creates the ASG with terraform.  https://gist.github.com/afterthought/1d4ad060ed52f23bd2af

I don't have it setup for anything "automatic" to kick off. In fact, based on our discussion I'm not planning to use kubernetes to expand the cluster at all now. The plan "was" to just use the k8 replication controller for couchbase to scale new pods. Now if/when I need to scale, I'll just add more non-ASG nodes to the cluster and use fleet. I'll still be using kubernetes for running the rest of our services.

**Comment by tleyden** [comment]
@afterthought thanks.

@PaulCapestany do you have the terraform scripts online anywhere?

**Comment by PaulCapestany** [comment]
@tleyden yup, I'd posted my terraform stuff up at [couchbase-sync-gateway-terraform](https://github.com/couchbase/kubernetes/issues/27#issuecomment-142073445)
