### ISSUE TITLE
Azure Efforts/Possibilities

### ISSUE THREAD

**Issue by coreyperkins** [couchbase/kubernetes#28]
Is anyone working on an Azure impl? I have tinkered with the Kube guide for CoreOS on Azure as well the Ubuntu guide. I would be interested in helping. Thanks!

**Comment by tleyden** [comment]
Not that I've heard of -- would be a welcome contribution! 

If you do, please write up some docs and I'll make sure to get it on the wiki: https://github.com/couchbase/kubernetes/wiki

**Comment by tleyden** [comment]
I'm closing the ticket as there are no immediate action items for the project owners, but feel free to continue the conversation on the ticket.
