### ISSUE TITLE
What about running 4.0 on GKE?

### ISSUE THREAD

**Issue by derekperkins** [couchbase/kubernetes#3]
Is this possible yet?

**Comment by tleyden** [comment]
Looks like that's the default:

https://github.com/couchbase/kubernetes/blob/master/replication-controllers/couchbase-server.yaml#L22

but I think there is a more recent version that we should be using.

**Comment by derekperkins** [comment]
Awesome, thanks for the quick fix!! I can't wait to get started!

PS. I've been looking all over the web for info on running Couchbase on GKE and only found this repo after digging through a lot of forum entries. Maybe a blog post would help raise the visibility?
