### ISSUE TITLE
Expose 8092 for views query.

### ISSUE THREAD

**Issue by snejati86** [couchbase/kubernetes#31]

**Comment by tleyden** [comment]
@snejati86 thanks!  I will lookup the syntax for exposing multiple container ports.  If you have any references to docs it would be useful.

**Comment by snejati86** [comment]
@tleyden I'll put a tiny pull request shortly, testing it with my current Kubernetes cluster now.

**Comment by tleyden** [comment]
Cool!!

**Comment by snejati86** [comment]
Pending #32
