### ISSUE TITLE
Requesting for a sample Couchbase cluster deployment using Couchbase Operator

### ISSUE THREAD

**Issue by VarunUmesh** [couchbase/kubernetes#42]
Could you please post a sample Couchbase cluster deployment using Couchbase Operator?

**Comment by tleyden** [comment]
AFAIK the couchbase operator hasn't been officially released yet!  Please ask on forums.couchbase.com

**Comment by tleyden** [comment]
@tahmmee is there a beta version of the Couchbase Operator that community users can test drive?
