### ISSUE TITLE
Setup Time

### ISSUE THREAD

**Issue by derekperkins** [couchbase/kubernetes#7]
I ran the demo setup with an f1-micro rather than a g1-small. It's been over an hour and all my pods listed for `kubectl get pods` are still pending, with the CPU pegged the entire time. How long should I expect the setup to take?

**Comment by tleyden** [comment]
I think you are running with too little resources.  See http://docs.couchbase.com/admin/admin/Concepts/bp-sizingGuidelines.html

**Comment by tleyden** [comment]
Actually this doc may be better: http://docs.couchbase.com/admin/admin/Install/install-resourceReqs.html

**Comment by derekperkins** [comment]
That's very helpful, thank you very much.
